const environment = {
  AUTH_SECRET: process.env.NEXTAUTH_SECRET,
  PUBLIC_SUPABASE_JWT_SECRET: process.env.NEXT_PUBLIC_SUPABASE_JWT_SECRET,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
};

export default environment;
